Repository vim-vdebug/vdebug, pull requests merged in 2019-07, with the labels that each got.

#402 Making the window height/width and status bar configurable
  plugin/vdebug.vim
  python3/vdebug/ui/vimui.py
Labels: enhancement

#404 Adding support for breakpoint enabling/disabling (Solve #393)
  plugin/vdebug.vim
  python3/vdebug/breakpoint.py
  python3/vdebug/dbgp.py
  python3/vdebug/debugger_interface.py
  python3/vdebug/event.py
  python3/vdebug/ui/vimui.py
  python3/vdebug/util.py
Labels: enhancement

#406 Adding a heartbeat
  python3/vdebug/session.py
Labels: enhancement

#407 Reports to the user if the port they want is already taken
  python3/vdebug/connection.py
Labels: enhancement

#412 Allow removing a breakpoint from an empty line
  python3/vdebug/event.py
Labels: bug

#415 when coming back from eval, pass context 0 to the event
  python3/vdebug/debugger_interface.py
Labels: bug

#416 first check connection before detaching
  python3/vdebug/session.py
Labels: bug

#417 add more clarity to the Vdebug_load_keymaps function
  plugin/vdebug.vim
Labels: enhancement

#418 convert status to str first and check if it exists
  python3/vdebug/event.py
Labels: bug

#413 Adding the ability to change stacks
  plugin/vdebug.vim
  python3/vdebug/dbgp.py
  python3/vdebug/debugger_interface.py
  python3/vdebug/event.py
  python3/vdebug/ui/vimui.py
Labels: enhancement

#419 first check if there is a connection before acting on some events
  python3/vdebug/event.py
Labels: enhancement

#421 Documentation
  doc/Vdebug.txt
Labels: documentation
